version: '3'

services:
  city-service:
    build: .
    restart: always
    links:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
