version: '3'

services:
  city-service:
    image: city-service:latest
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/city_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: