version: '1'

services:
  user-service:
    image: city-service:latest
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/city_service
      - SPRING_PROFILES_ACTIVE=local

  postgres:
    image: postgres:14.5
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city_service